#include "MicroBit.h"
#include "samples/Tests.h"

MicroBit uBit;

int main()
{
    DMESG( "CONFIG_MICROBIT_ERASE_USER_DATA_ON_REFLASH %d", (int) CONFIG_MICROBIT_ERASE_USER_DATA_ON_REFLASH);
    DMESG( "SOFTDEVICE_PRESENT %d", (int) SOFTDEVICE_PRESENT);
    DMESG( "DEVICE_BLE %d", (int) DEVICE_BLE);
    DMESG( "MICROBIT_BLE_ENABLED %d", (int) MICROBIT_BLE_ENABLED);
    DMESG( "MICROBIT_BLE_PAIRING_MODE %d", (int) MICROBIT_BLE_PAIRING_MODE);
    DMESG( "DMESG_SERIAL_DEBUG %d", (int) DMESG_SERIAL_DEBUG);
    DMESG( "DEVICE_DMESG_BUFFER_SIZE %d", (int) DEVICE_DMESG_BUFFER_SIZE);

    uBit.init();

    out_of_box_experience();
}